name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  run-demo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@v7

      - run: uv run demo.py

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@v7

      - run: uv build --no-sources

  create-snapshot:
    uses: ./.github/workflows/create-snapshot.yaml
    with:
      artifact-name: snapshot

  compare-snapshot:
    needs: create-snapshot
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - run: rm -rf test/snapshot

      - name: Download snapshots
        uses: actions/download-artifact@v5
        with:
          name: snapshot
          path: test/snapshot

      - name: Compare snapshots
        run: |
          git add --intent-to-add test/snapshot
          git diff --exit-code test/snapshot
