name: Publish package to PyPI

on:
  push:
    tags: ["**"]

permissions:
  contents: read

env:
  UV_VERSION: 0.6.16

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: false

      - run: uv build --no-sources

      - run: uv publish
