name: Publish package to PyPI

on: workflow_dispatch

permissions:
  contents: read

concurrency: ${{ github.workflow }}

env:
  RYE_VERSION: 0.31.0

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rye
        run: |
          TEMP_FILE=$(mktemp)
          curl -fsSL "https://github.com/mitsuhiko/rye/releases/download/$RYE_VERSION/rye-x86_64-linux.gz" | gunzip > "$TEMP_FILE"
          chmod +x "$TEMP_FILE"
          "$TEMP_FILE" self install --yes
          rm "$TEMP_FILE"
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Build
        run: rye build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          compression-level: 0

  publish:
    needs: build
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
